server:
  port: 8072
spring:
  application:
    name: subscriber-app
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true
  jms:
    topic-name: "topic.st01"
    durable-client-id: durable-subscriber
    non-durable-client-id: non-durable-subscriber

logging:
  level:
    root: error
    com:
      tananushka:
        mom:
          subscriberapp:
            subscriber: info